CREATE DATABASE IF NOT EXISTS sdai_report_db;

USE sdai_report_db;

CREATE TABLE IF NOT EXISTS reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    image LONGTEXT NOT NULL,
    server_source VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER IF NOT EXISTS 'PLACEHOLDER_USER'@'%' IDENTIFIED BY 'PLACEHOLDER_PASSWORD';

GRANT ALL PRIVILEGES ON sdai_report_db.* TO 'PLACEHOLDER_USER'@'%';

FLUSH PRIVILEGES;
